
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 827007343006318593
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 16
	updater = false

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Taking forever to load..."
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[init.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "In awe of the menu"
	#The seconds line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[main_menu.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[server_list.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogonew"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Trying to start an adventure"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[join_game.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently in %world%"
	#The second line of text under the app name
	state = "Playing lonely mode"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[single_player.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% with %players% players"
	#The second line of text under the app name
	state = "Found some friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[multi_player.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogonew"
	#The text that gets displayed when the large image is hovered
	largeImageText = "It's Minecraft %mcver%, but modded"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Dimension Hopper"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "mclogo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Dimension Hopper: The Fall V1.5.8.2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[generic.buttons]]
		label = "Discord"
		url = "https://discord.gg/ZqDdytk"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = "mclogo"
		largeImageText = "In the Overworld"
		smallImageKey = "loading"
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = "mclogo"
		largeImageText = "In the Nether"
		smallImageKey = "loading"
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = "mclogo"
		largeImageText = "In the End"
		smallImageKey = "loading"
		smallImageText = "%mods% mods installed"
		buttons = []

